<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HoZInV2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hoZInV2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hoZInV2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'grpRepo' => ['privates', 'App\\Repository\\GroupeCompetenceRepository', 'getGroupeCompetenceRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'grpRepo' => 'App\\Repository\\GroupeCompetenceRepository',
            'serializer' => '?',
        ]);
    }
}
