<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EAP4qd8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EAP4qd8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EAP4qd8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'profilRepo' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService', true],
            'user_service' => ['privates', 'App\\Services\\UserServices', 'getUserServicesService', true],
        ], [
            'em' => '?',
            'profilRepo' => 'App\\Repository\\ProfilRepository',
            'user_service' => 'App\\Services\\UserServices',
        ]);
    }
}
