<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DLmHfvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DLm_Hfv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DLm_Hfv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\GroupeApprenantController::addGroupeApprenant' => ['privates', '.service_locator.QxA.LiJ', 'get_ServiceLocator_QxA_LiJService', true],
            'App\\Controller\\GroupeApprenantController::putGroupeApprenant' => ['privates', '.service_locator.UII78XM', 'get_ServiceLocator_UII78XMService', true],
            'App\\Controller\\ReferentielController::add_referentiels' => ['privates', '.service_locator.5KxDtMZ', 'get_ServiceLocator_5KxDtMZService', true],
            'App\\Controller\\ReferentielController::put_referentiel' => ['privates', '.service_locator.KkHakch', 'get_ServiceLocator_KkHakchService', true],
            'App\\Controller\\ReferentielController::read_referentiel_grp_skills_only' => ['privates', '.service_locator.hoZInV2', 'get_ServiceLocator_HoZInV2Service', true],
            'App\\Controller\\UserController::add_user' => ['privates', '.service_locator.EAP4qd8', 'get_ServiceLocator_EAP4qd8Service', true],
            'App\\Controller\\UserController::put_user' => ['privates', '.service_locator.ag13N5S', 'get_ServiceLocator_Ag13N5SService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\GroupeApprenantController:addGroupeApprenant' => ['privates', '.service_locator.QxA.LiJ', 'get_ServiceLocator_QxA_LiJService', true],
            'App\\Controller\\GroupeApprenantController:putGroupeApprenant' => ['privates', '.service_locator.UII78XM', 'get_ServiceLocator_UII78XMService', true],
            'App\\Controller\\ReferentielController:add_referentiels' => ['privates', '.service_locator.5KxDtMZ', 'get_ServiceLocator_5KxDtMZService', true],
            'App\\Controller\\ReferentielController:put_referentiel' => ['privates', '.service_locator.KkHakch', 'get_ServiceLocator_KkHakchService', true],
            'App\\Controller\\ReferentielController:read_referentiel_grp_skills_only' => ['privates', '.service_locator.hoZInV2', 'get_ServiceLocator_HoZInV2Service', true],
            'App\\Controller\\UserController:add_user' => ['privates', '.service_locator.EAP4qd8', 'get_ServiceLocator_EAP4qd8Service', true],
            'App\\Controller\\UserController:put_user' => ['privates', '.service_locator.ag13N5S', 'get_ServiceLocator_Ag13N5SService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\GroupeApprenantController::addGroupeApprenant' => '?',
            'App\\Controller\\GroupeApprenantController::putGroupeApprenant' => '?',
            'App\\Controller\\ReferentielController::add_referentiels' => '?',
            'App\\Controller\\ReferentielController::put_referentiel' => '?',
            'App\\Controller\\ReferentielController::read_referentiel_grp_skills_only' => '?',
            'App\\Controller\\UserController::add_user' => '?',
            'App\\Controller\\UserController::put_user' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\GroupeApprenantController:addGroupeApprenant' => '?',
            'App\\Controller\\GroupeApprenantController:putGroupeApprenant' => '?',
            'App\\Controller\\ReferentielController:add_referentiels' => '?',
            'App\\Controller\\ReferentielController:put_referentiel' => '?',
            'App\\Controller\\ReferentielController:read_referentiel_grp_skills_only' => '?',
            'App\\Controller\\UserController:add_user' => '?',
            'App\\Controller\\UserController:put_user' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
