<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UII78XMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UII78XM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UII78XM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apprenantRepo' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'grpAppRepo' => ['privates', 'App\\Repository\\GroupeApprenantRepository', 'getGroupeApprenantRepositoryService', true],
        ], [
            'apprenantRepo' => 'App\\Repository\\ApprenantRepository',
            'em' => '?',
            'grpAppRepo' => 'App\\Repository\\GroupeApprenantRepository',
        ]);
    }
}
