<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeApprenantControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GroupeApprenantController' shared autowired service.
     *
     * @return \App\Controller\GroupeApprenantController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GroupeApprenantController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/GroupeApprenantServices.php';

        $container->services['App\\Controller\\GroupeApprenantController'] = $instance = new \App\Controller\GroupeApprenantController(new \App\Services\GroupeApprenantServices(($container->services['serializer'] ?? $container->getSerializerService()), ($container->services['validator'] ?? $container->getValidatorService())));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\GroupeApprenantController', $container));

        return $instance;
    }
}
