<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReferentielServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ReferentielServices' shared autowired service.
     *
     * @return \App\Services\ReferentielServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ReferentielServices.php';

        return $container->privates['App\\Services\\ReferentielServices'] = new \App\Services\ReferentielServices(($container->services['serializer'] ?? $container->getSerializerService()), ($container->services['validator'] ?? $container->getValidatorService()));
    }
}
