<?php

namespace ContainerTQNaOsj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\UserServices' shared autowired service.
     *
     * @return \App\Services\UserServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/UserServices.php';

        return $container->privates['App\\Services\\UserServices'] = new \App\Services\UserServices(($container->services['serializer'] ?? $container->getSerializerService()), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['validator'] ?? $container->getValidatorService()));
    }
}
